> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [5]:
!pip install jovian --upgrade -q

In [6]:
import jovian

In [7]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "jforjha/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/jforjha/numpy-array-operations


'https://jovian.ai/jforjha/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [8]:
import numpy as np

In [10]:
# List of functions explained 
function1 = np.concatenate  # (change this)
function2 = np.dot
function3 = np.matmul
function4 = np.reshape
function5 = np.zeros

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [11]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example

In [22]:
# Example 2 - working
arr1 = [[1, 2,9], 
        [3, 4.,10]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]
result = np.concatenate((arr1,arr2),axis=1)
print(result)

[[ 1.  2.  9.  5.  6.  7.]
 [ 3.  4. 10.  8.  9. 10.]]


Explanation about example

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [24]:
# It breaks because Input array must have the same dimensions for the concatenation

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [25]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "jforjha/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/jforjha/numpy-array-operations


'https://jovian.ai/jforjha/numpy-array-operations'

## Function 2 - ???

Add some explanations

In [28]:
# Example 1 - working
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6], 
        [8, 9]]
result = np.dot(arr1, arr2)

print(result)

[[21. 24.]
 [47. 54.]]


Explanation about example

In [33]:
# Example 2 - working
arr1 = np.array([1, 2, 3, 3, 4, 5])
arr2 = np.array([2, 2, 3,1, 2, 5])
result = np.dot(arr1,arr2)
print(result)

51


Explanation about example

In [35]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([1, 2, 3, 3, 4, 5])
arr2 = np.array([2, 2, 3,1, 5])
result = np.dot(arr1,arr2)
print(result)
#shapes are not aligne and of not same dimension

ValueError: shapes (6,) and (5,) not aligned: 6 (dim 0) != 5 (dim 0)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [36]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "jforjha/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/jforjha/numpy-array-operations


'https://jovian.ai/jforjha/numpy-array-operations'

## Function 3 - ???

Add some explanations

In [37]:
# Example 1 - working
arr1 = np.array([1,2,3,4])
arr2=np.array([4,5,6,7])
np.matmul(arr1,arr2)

60

Explanation about example

In [45]:
# Example 2 - working
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
weights = np.array([0.3, 0.2, 0.5])
yields = np.matmul(climate_data , weights)
print(yields)

[72.2 59.7 65.2 ... 71.1 80.7 73.4]


Explanation about example

In [54]:
# Example 3 - breaking (to illustrate when it breaks)
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)
yields = np.matmul(climate_data , weights)
if yields == true:
print("orrect")
else :
pint("always Wrong")


IndentationError: expected an indented block (<ipython-input-54-29cc485afdd2>, line 5)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [55]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "jforjha/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/jforjha/numpy-array-operations


'https://jovian.ai/jforjha/numpy-array-operations'

## Function 3 - ???

Add some explanations

In [56]:
# Example 1 - working
arr1 = np.array([1,2,3,4])
arr2=np.array([4,5,6,7])
np.matmul(arr1,arr2)

60

Explanation about example

In [57]:
# Example 2 - working
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
weights = np.array([0.3, 0.2, 0.5])
yields = np.matmul(climate_data , weights)
print(yields)

[72.2 59.7 65.2 ... 71.1 80.7 73.4]


Explanation about example

In [58]:
# Example 3 - breaking (to illustrate when it breaks)
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)
yields = np.matmul(climate_data , weights)
if yields == true:
print("orrect")
else :
pint("always Wrong")

IndentationError: expected an indented block (<ipython-input-58-29cc485afdd2>, line 5)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [59]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "jforjha/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/jforjha/numpy-array-operations


'https://jovian.ai/jforjha/numpy-array-operations'

## Function 4 - ???

Add some explanations

In [60]:
# Example 1 - working
#np.reshape()=Reshaping means changing the shape of an array.

#The shape of an array is the number of elements in each dimension.

#By reshaping we can add or remove dimensions or change number of elements in each dimension.

Explanation about example

In [61]:
# Example 2 - working
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Explanation about example

In [62]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 30)

print(newarr)

ValueError: cannot reshape array of size 12 into shape (4,30)

Explanation about example (why it breaks and how to fix it)

In [63]:
#It Breaks it cant reshape more than its elements

Some closing comments about when to use this function.

In [64]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "jforjha/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/jforjha/numpy-array-operations


'https://jovian.ai/jforjha/numpy-array-operations'

## Function 5 - ???

Add some explanations

In [ ]:
# Example 1 - working
#syntax
# numpy.zeros(shape, dtype = None, order = 'C')


Explanation about example

In [67]:
# Example 2 - working
b = np.zeros(2, dtype = int) 
print("Matrix b : \n", b) 

Matrix b : 
 [0 0]


Explanation about example

In [69]:
# Example 3 - breaking (to illustrate when it breaks)
b = np.zeros(2, dtype = string) 
print("Matrix b : \n", b) 

NameError: name 'string' is not defined

Explanation about example (why it breaks and how to fix it)

In [ ]:
# It Breaks because string is not defined in 

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [1]:
jovian.commit()


<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/jforjha/numpy-array-operations


'https://jovian.ai/jforjha/numpy-array-operations'